# ==============================================================================
# File        : inventory.ini
# Description : Public example inventory template for Linux system hardening
# Author      : SudoShea
# Version     : 1.1.0
# License     : MIT
# ==============================================================================

[debian_nodes]
# debian-node-01.example.com ansible_host=192.0.2.10

[rhel_nodes]
# rhel-node-01.example.com ansible_host=192.0.2.20

[hardening:children]
debian_nodes
rhel_nodes

[hardening:vars]
ansible_user=<username>
ansible_become=true
ansible_python_interpreter=/usr/bin/python3
